### ISSUE TITLE
얼라인먼트 생성 관련 문의

### ISSUE THREAD

**Issue by Infoholic-GitHub** [ORI-Muchim/Efficient-Speech#1]
안녕하세요, 이 프로젝트를 클론해서 커스텀 데이터셋을 만드는데 써보고 있는데, wav 파일이 1000개를 넘어가다보니 수동으로 텍스트그리드를 생성하는 것이 현실적으로 어렵습니다. 그 대신 MFA 얼라이너를 훈련시켜보려고 했으나 결과가 썩 만족스럽지 않은데, 혹시 텍스트 그리드 생성 모델을 훈련시키신 바가 있다면 어떻게 하셨는지 조언을 주실 수 있을까요?

**Comment by ORI-Muchim** [comment]
죄송합니다. 
이슈를 남겨주셨군요. 지금 봤습니다. 이메일을 통한 대화에서 도움이 되셨으면 좋겠습니다.
이슈는 잠시 닫아두겠습니다. 감사합니다.
